### ISSUE TITLE
Redirection faild 

### ISSUE THREAD

**Issue by ngfw** [marcinwol/zfopenid#1]
I'm getting 
object(Zend_Auth_Result)#107 (3) {
 ["_code":protected]=> int(0)
 ["_identity":protected]=> string(37) "https://www.google.com/accounts/o8/id" 
 ["_messages":protected]=> array(2) { 
    [0]=> string(21) "Authentication failed" 
    [1]=> string(43) "Association failed: Could not create digest" 
    }
 }

Any ideas?
Thanks

**Comment by marcinwol** [comment]
Does this happen on the demo application?

**Comment by ngfw** [comment]
No, Demo is fine, Happens when I checkout from Git, and the problem is only for Google and Yahoo. others are fine.

**Comment by jerkan** [comment]
I experienced same as gejadze. 

I downloaded the code and tried to log with Google and Yahoo but I get 'redirection faild'

**Comment by marcinwol** [comment]
Hi,

Do you get any other messages? I ask since I cannot replicate the problem on localhost with xampp 1.7.3a on Linux x86.

Also do you use zend framework code that comes with my zfopenid example?

**Comment by ngfw** [comment]
For me it was an issue with sessions, I believe it was something in the PHP configuration, Updated to latest version and it works fine.

**Comment by dudapiotrek** [comment]
Hey,
I had the same problem and to resolve that, we should enable extension=php_openssl.dll in php.ini.
