### ISSUE TITLE
Twitter authentication

### ISSUE THREAD

**Issue by ghost** [marcinwol/zfopenid#2]
Thanks for the useful code.  One issue I found was that Twitter had to reauthorise every time the user logs in.  I fixed this by setting authorizeUrl to /authenticate instead of the default /authorize, by adding it to  _oauthConfig:

```
    $this->_oathConfig = array(
        'callbackUrl' => $this->_callbackUrl,
        'siteUrl' => 'http://twitter.com/oauth',
        'authorizeUrl' => 'https://api.twitter.com/oauth/authenticate',
        'consumerKey' => $this->_consumerKey,
        'consumerSecret' => $this->_consumerSecret,
    );
```

**Comment by marcinwol** [comment]
Thanks for the info. I'll have a look at this.

Kind regards

On Thu, Jul 28, 2011 at 12:24 PM, gumnut
reply@reply.github.com
wrote:

**Comment by marcinwol** [comment]
I made the change. 
Thanks.
